create model auth user and user actives
bigbang-theory/saturnus-backend pull request #2
Opened 2023-04-06 04:53 UTC by abuamar142

2023-04-06 06:12 UTC, ilhaammulia requested changes

2023-04-06 06:12 UTC, ilhaammulia commented on users/models/user_actives.py
user_id nya jangan dikasih default, kan harus ada isinya yang dari auth_user. nullable nya di false juga

2023-04-06 07:28 UTC, abuamar142 commented on users/models/user_actives.py
baik ham

2023-04-06 08:24 UTC, ilhaammulia commented on users/models/user_actives.py
user_id = sqlalchemy.Column(sqlalchemy.String, primary_key=True)

tetep kolom biasa user_id nya, bukan foreign key

2023-04-07 05:14 UTC, ilhaammulia approved these changes

2023-04-07 05:15 UTC, merged